### ISSUE TITLE
WELP

### ISSUE THREAD

**Issue by WeskerPower** [Tibia-WindBot/raphael-library#15]
theres no developer branch

`local function GoldConverter(BackpackFrom, BackpackTo, Cap)
-- BackpackFrom Where are your Gold Coins
-- BackpackTo Backpack to move uncomplete stack
-- Cap to use gold converter [this is how it should be used]
local cont = getcontainer(BackpackFrom)
local cont1 = getcontainer(BackpackTo)
local coins = itemcount(3031,BackpackFrom)

if $cap < Cap and coins > 100 and itemcount(23722) > 0 then
for j=1,cont.itemcount do
if cont.item[j].count < 100 and cont.item[j].id == 3031 then
        moveitems(3031,BackpackTo,BackpackFrom,cont.item[j].count)
elseif cont.item[j].count == 100 and cont.item[j].id == 3031 then
        useitemon(23722, 3031, BackpackFrom)
end
end
end
if itemcount(3031,BackpackTo) > 0 then
moveitems(3031, BackpackFrom, BackpackTo, 100)
end
end

GoldConverter("Jewelled Backpack", "Zaoan Chess Box", 190)`

feel free to update anything

**Comment by TheJoshGriffith** [comment]
This isn't a bug report, it's a shambles. What exactly is the bug?

**Comment by leonardofalk** [comment]
First of all I want to thank you for your PR @WeskerPower, but I'll ask some changes so we can extract the maximum functionality out of this.

Hoewever, I don't think it should be integrated with the library because it doesn't have any effect on scripting new code, it's a script wrapped in a function, and we want to avoid that (you can see some functions of my lib have this same behaviour, and that's why they're deprecated now), although I see you've put some effort on it, I'll tell you how we can work this out.

You can write this code again, this time following ~the [Lua style guide](https://github.com/Olivine-Labs/lua-style-guide)~ [our own Lua style guides](https://github.com/Tibia-WindBot/lua-style-guide), making it soft coded as much as it needs to be, for example what if I wanted to use other criteria other than the capacity? Now it's hard to change it, since you only allowed the capacity to be usable. That should be configurable and easy as possible so any final user could do it by him/herself.

**Comment by rmobis** [comment]
As @leonardofalk pointed out, I don't believe this function fits the kind of work we're developing here. It has very little value when mixed with other code so it would be better suited as a script on the Lua Scripts section.

I'm closing this.
